silant_main/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

urlpatterns = [
    path('', include('allauth.urls')),
    path('account_list', AccountList.as_view(), name='account_list'),
    path('account_list/<int:pk>', AccountItem.as_view()),
    path('account_list/<int:pk>/edit', EditAccount.as_view()),
    path('account_list/create_account', CreateAccount.as_view(), name='create_account'),
]

silant_main/services/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('index', Index.as_view()),

    path('info', Info.as_view(), name='info'),
    path('info/<int:pk>', InfoItem.as_view()),
    path('info/<int:pk>/edit', EditCar.as_view()),
    path('info/<int:pk>/delete', DeleteCar.as_view()),
    path('create_car', CreateCar.as_view(), name='create_car'),

    path('maintenance', MaintenanceList.as_view(), name='maintenance'),
    path('maintenance/<int:pk>', MaintenanceItem.as_view()),
    path('maintenance/<int:pk>/edit', MaintenanceEdit.as_view()),
    path('maintenance/<int:pk>/delete', MaintenanceDelete.as_view()),
    path('create_maintenance', CreateMaintenances.as_view(), name='create_maintenance'),

    path('complaints', ComplaintsList.as_view(), name='complaints'),
    path('complaints/<int:pk>', ComplaintsItem.as_view()),
    path('complaints/<int:pk>/edit', ComplaintsEdit.as_view()),
    path('complaints/<int:pk>/delete', ComplaintsDelete.as_view()),
    path('create_complaints', CreateComplaints.as_view(), name='create_complaints'),

    path('reference_book/', reference_book, name='reference_book'),
    path('reference_book/<int:pk>/', ReferenceBookList.as_view()),
    # path('reference_book/<int:pk>/', ReferenceBookList.as_view()),
    path('reference_book/1/create/', TechniqueModeCreate.as_view()),
    path('reference_book/1/<int:pk>/edit/', TechniqueModelEdit.as_view()),
    path('reference_book/2/create/', EngineModelCreate.as_view()),
    path('reference_book/2/<int:pk>/edit/', EngineModelEdit.as_view()),
    path('reference_book/3/create/', TransmissionModelCreate.as_view()),
    path('reference_book/3/<int:pk>/edit/', TransmissionModelEdit.as_view()),
    path('reference_book/4/create/', DriveAxleModelCreate.as_view()),
    path('reference_book/4/<int:pk>/edit/', DriveAxleModelEdit.as_view()),
    path('reference_book/5/create/', SteerableAxleModelCreate.as_view()),
    path('reference_book/5/<int:pk>/edit/', SteerableAxleModelEdit.as_view()),
    path('reference_book/6/create/', ServiceCompanyCreate.as_view()),
    path('reference_book/6/<int:pk>/edit/', ServiceCompanyEdit.as_view()),
    path('reference_book/7/create/', TypeMaintenanceCreate.as_view()),
    path('reference_book/7/<int:pk>/edit/', TypeMaintenanceEdit.as_view()),
    path('reference_book/8/create/', DescriptionFailureCreate.as_view()),
    path('reference_book/8/<int:pk>/edit/', DescriptionFailureEdit.as_view()),
    path('reference_book/9/create/', RecoveryMethodCreate.as_view()),
    path('reference_book/9/<int:pk>/edit/', RecoveryMethodEdit.as_view()),

]

silant_main/silant_main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static


urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('accounts.urls')),
  path('', include('services.urls')),
  path('api_silant/', include('api_silant.urls')),
]
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),]

silant_main/services/models.py
from django.db import models
from django.contrib.auth.models import User


class CustomUser(User):
    class Meta:
        proxy = True

    def __str__(self):
        return self.first_name


class Technique_model(models.Model):
    name = models.TextField(unique=True, verbose_name='Title')
    description = models.TextField(blank=True, verbose_name='Description')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Model of machines' 
        verbose_name_plural = 'Models of machines'


class Engine_model(models.Model):
    name = models.TextField(unique=True, verbose_name='Title')
    description = models.TextField(blank=True, verbose_name='Description')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Engine model'
        verbose_name_plural = 'Engine models'


class Transmission_model(models.Model):
    name = models.TextField(unique=True, verbose_name='Title')
    description = models.TextField(blank=True, verbose_name='Description')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Transmission model'
        verbose_name_plural = 'Transmission models'


class Drive_axle_model(models.Model):
    name = models.TextField(unique=True, verbose_name='Title')
    description = models.TextField(blank=True, verbose_name='Description')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Drive axle model'
        verbose_name_plural = 'Drive axle models'


class Steerable_axle_model(models.Model):
    name = models.TextField(unique=True, verbose_name='Title')
    description = models.TextField(blank=True, verbose_name='Description')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Steering axle model'
        verbose_name_plural = 'Steering axle models'


class Service_company(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, verbose_name='Username')
    name = models.TextField(unique=True, verbose_name='Title')
    description = models.TextField(blank=True, verbose_name='Description')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Service company'
        verbose_name_plural = 'Service companies'


class Car(models.Model):
    factory_number = models.TextField(max_length=17, unique=True, db_index=True, verbose_name='Factory number')
    technique_model = models.ForeignKey(Technique_model, on_delete=models.CASCADE, db_index=True, verbose_name='Vehicle model')
    engine_model = models.ForeignKey(Engine_model, on_delete=models.CASCADE, db_index=True, verbose_name='Engine model')
    engine_number = models.TextField(max_length=17, verbose_name='Engine number')
    transmission_model = models.ForeignKey(Transmission_model, on_delete=models.CASCADE, db_index=True, verbose_name='Transmission model')
    transmission_number = models.TextField(max_length=50, verbose_name='Transmission number')
    drive_axle_model = models.ForeignKey(Drive_axle_model, on_delete=models.CASCADE, db_index=True, verbose_name='Drive axle model')
    drive_axle_number = models.TextField(max_length=50, verbose_name='Drive axle number')
    steerable_axle_model = models.ForeignKey(Steerable_axle_model, on_delete=models.CASCADE, db_index=True, verbose_name='Steering axle model')
    steerable_axle_number = models.TextField(max_length=50, verbose_name='Steering axle number')
    supply_contract = models.TextField(max_length=50, blank=True, verbose_name='Delivery agreement No., date.')
    date_of_shipment_from_the_factory = models.DateField(db_index=True, verbose_name='Дата отгрузки с завода')
    consignee = models.TextField(max_length=50, blank=True, verbose_name='Consignee')
    delivery_address = models.TextField(max_length=300, blank=True, verbose_name='Delivery (operation) address')
    equipment = models.TextField(blank=True, verbose_name='Equipment (additional options)')
    client = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Client')
    service_company = models.ForeignKey(Service_company, null=True, on_delete=models.CASCADE, blank=True, verbose_name='Service organization')

    def __str__(self):
        return f'{self.factory_number}'

    class Meta:
        verbose_name = 'Car'
        verbose_name_plural = 'Cars'
        ordering = ['date_of_shipment_from_the_factory']


class Type_maintenance(models.Model):
    name = models.TextField(verbose_name='Title')
    description = models.TextField(blank=True, verbose_name='Description')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Type TO'
        verbose_name_plural = 'Types TO'


class Maintenance(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Car')
    service_company = models.ForeignKey(Service_company, on_delete=models.CASCADE, verbose_name='Service organization')
    type_maintenance = models.ForeignKey(Type_maintenance, on_delete=models.CASCADE, verbose_name='Type TO')
    maintenance_date = models.DateField(verbose_name='Maintenance date')
    operating_time = models.IntegerField(verbose_name='Earning moto/hours')
    order = models.TextField(max_length=50, verbose_name='Work order number')
    order_date = models.DateField(verbose_name='Work order date')

    def __str__(self):
        return f'{self.car, self.type_maintenance}'

    class Meta:
        verbose_name = 'ТО'
        verbose_name_plural = 'ТО'
        ordering = ['maintenance_date']



class Description_failure(models.Model):
    name = models.TextField(verbose_name='Title')
    description = models.TextField(blank=True, verbose_name='Description')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Nature of failure'
        verbose_name_plural = 'Nature of failures'


class Recovery_method(models.Model):
    name = models.TextField(verbose_name='Title')
    description = models.TextField(blank=True, verbose_name='Description')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Recovery method'
        verbose_name_plural = 'Recovery methods'


class Complaints(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Car')
    service_company = models.ForeignKey(Service_company, on_delete=models.CASCADE, verbose_name='Service organization')
    date_of_refusal = models.DateField(verbose_name='Date of refusal')
    operating_time = models.IntegerField(verbose_name='Operating hours m/hour')
    failure_node = models.TextField(verbose_name='Failure node')
    description_failure = models.ForeignKey(Description_failure, on_delete=models.CASCADE, verbose_name='Nature of failure')
    recovery_method = models.ForeignKey(Recovery_method, on_delete=models.CASCADE, verbose_name='Recovery method')
    parts_used = models.TextField(blank=True, verbose_name='Spare parts used')
    date_of_restoration = models.DateField(verbose_name='Restore date')
    equipment_downtime = models.TextField(verbose_name='Equipment downtime')

    def __str__(self):
        return f'{self.car, self.failure_node}'

    class Meta:
        verbose_name = 'Complaints'
        verbose_name_plural = 'Complaints'
        ordering = ['date_of_refusal']

silant_main/services/forms.py
from django import forms
from .models import *

class FactoryNumber(forms.Form):
    factory_number = forms.CharField(label='Factory Number', widget=forms.TextInput(attrs={'size': 8}), max_length=10)

class CreateCarForm(forms.ModelForm):
    client = forms.ModelChoiceField(
        queryset=CustomUser.objects.filter(groups__name='client').order_by('first_name')
    )

    class Meta:
        model = Car
        widgets = {
            'factory_number': forms.Textarea(attrs={'rows': 1}),
            'engine_number': forms.Textarea(attrs={'rows': 1}),
            'transmission_number': forms.Textarea(attrs={'rows': 1}),
            'drive_axle_number': forms.Textarea(attrs={'rows': 1}),
            'steerable_axle_number': forms.Textarea(attrs={'rows': 1}),
            'supply_contract': forms.Textarea(attrs={'rows': 1}),
            'consignee': forms.Textarea(attrs={'rows': 1}),
            'delivery_address': forms.Textarea(attrs={'rows': 2}),
            'equipment': forms.Textarea(attrs={'rows': 5}),
            'date_of_shipment_from_the_factory': forms.NumberInput(attrs={'type': 'date'}),
        }
        fields = '__all__'

class CreateMaintenancesForm(forms.ModelForm):
    class Meta:
        model = Maintenance
        fields = '__all__'
        widgets = {
            'order': forms.Textarea(attrs={'rows': 1}),
            'maintenance_date': forms.NumberInput(attrs={'type': 'date'}),
            'order_date': forms.NumberInput(attrs={'type': 'date'}),
            'car': forms.HiddenInput(),
            'service_company': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        service_company = kwargs.pop('initial')['service_company']
        self.fields['service_company'].initial = service_company

class UpdateMaintenancesForm(forms.ModelForm):
    class Meta:
        model = Maintenance
        fields = '__all__'
        widgets = {
            'order': forms.Textarea(attrs={'rows': 1}),
            'maintenance_date': forms.NumberInput(attrs={'type': 'date'}),
            'order_date': forms.NumberInput(attrs={'type': 'date'}),
            'car': forms.HiddenInput(),
            'service_company': forms.HiddenInput()
        }

class CreateComplaintsForm(forms.ModelForm):
    class Meta:
        model = Complaints
        fields = '__all__'
        widgets = {
            'date_of_refusal': forms.NumberInput(attrs={'type': 'date'}),
            'failure_node': forms.Textarea(attrs={'rows': 1}),
            'parts_used': forms.Textarea(attrs={'rows': 1}),
            'date_of_restoration': forms.NumberInput(attrs={'type': 'date'}),
            'equipment_downtime': forms.Textarea(attrs={'rows': 1}),
            'car': forms.HiddenInput(),
            'service_company': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super(CreateComplaintsForm, self).__init__(*args, **kwargs)
        self.fields['service_company'].help_text = 'Managers in the vehicle information can assign or change the organization for this vehicle.'

class UpdateComplaintsForm(forms.ModelForm):
    class Meta:
        model = Complaints
        fields = '__all__'
        widgets = {
            'date_of_refusal': forms.NumberInput(attrs={'type': 'date'}),
            'failure_node': forms.Textarea(attrs={'rows': 1}),
            'parts_used': forms.Textarea(attrs={'rows': 1}),
            'date_of_restoration': forms.NumberInput(attrs={'type': 'date'}),
            'equipment_downtime': forms.Textarea(attrs={'rows': 1}),
            'car': forms.HiddenInput(),
            'service_company': forms.HiddenInput()
        }

class UpdateTechniqueModelForm(forms.ModelForm):
    class Meta:
        model = Technique_model
        fields = '__all__'
        widgets = {'name': forms.Textarea(attrs={'rows': 1})}

class UpdateEngineModelForm(forms.ModelForm):
    class Meta:
        model = Engine_model
        fields = '__all__'
        widgets = {'name': forms.Textarea(attrs={'rows': 1})}

class UpdateTransmissionModelForm(forms.ModelForm):
    class Meta:
        model = Transmission_model
        fields = '__all__'
        widgets = {'name': forms.Textarea(attrs={'rows': 1})}

class UpdateDriveAxleModelForm(forms.ModelForm):
    class Meta:
        model = Drive_axle_model
        fields = '__all__'
        widgets = {'name': forms.Textarea(attrs={'rows': 1})}

class UpdateSteerableAxleModelForm(forms.ModelForm):
    class Meta:
        model = Steerable_axle_model
        fields = '__all__'
        widgets = {'name': forms.Textarea(attrs={'rows': 1})}

class CreateServiceCompanyForm(forms.ModelForm):
    class Meta:
        model = Service_company
        fields = '__all__'
        widgets = {'name': forms.Textarea(attrs={'rows': 1})}

class UpdateServiceCompanyForm(forms.ModelForm):
    class Meta:
        model = Service_company
        fields = '__all__'
        widgets = {'name': forms.Textarea(attrs={'rows': 1}), 'user': forms.HiddenInput()}

class UpdateTypeMaintenanceForm(forms.ModelForm):
    class Meta:
        model = Type_maintenance
        fields = '__all__'
        widgets = {'name': forms.Textarea(attrs={'rows': 1})}

class UpdateDescriptionFailureForm(forms.ModelForm):
    class Meta:
        model = Description_failure
        fields = '__all__'
        widgets = {'name': forms.Textarea(attrs={'rows': 1})}

class UpdateRecoveryMethodForm(forms.ModelForm):
    class Meta:
        model = Recovery_method
        fields = '__all__'
        widgets = {'name': forms.Textarea(attrs={'rows': 1})}

silant_main/services/templates/car_item.html
{% extends 'default.html' %}
{% load auth_extras %}
{% load bootstrap5 %}
{% block bootstrap_css %}{% bootstrap_css %}{% bootstrap_javascript %}{% endblock bootstrap_css %}

{% block content %}

<h5 class="center">Data of the Selected Machine:</h5>

<div class="center">
    <table style="border-bottom: none; border-top: none;">
    <tr><td>Machine Factory Number:</td><td>{{ car.factory_number }}</td></tr>
    <tr><td>Technique Model:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#technique_model">
        <b>{{ car.technique_model }}</b></a></td></tr>
    <tr><td>Engine Model:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#engine_model">
        <b>{{ car.engine_model }}</b></a></td></tr>
    <tr><td>Engine Factory Number:</td><td>{{ car.engine_number }}</td></tr>
    <tr><td>Transmission Model:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#transmission_model">
        <b>{{ car.transmission_model }}</b></a></td></tr>
    <tr><td>Transmission Factory Number:</td><td>{{ car.transmission_number }}</td></tr>
    <tr><td>Drive Axle Model:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#drive_axle_model">
        <b>{{ car.drive_axle_model }}</b></a></td></tr>
    <tr><td>Drive Axle Factory Number:</td><td>{{ car.drive_axle_number }}</td></tr>
    <tr><td>Steerable Axle Model:</td>
        <td><a href="#" data-bs-toggle="modal" data-bs-target="#steerable_axle_model">
            <b>{{ car.steerable_axle_model }}</b></a></td></tr>
    <tr><td>Steerable Axle Factory Number:</td><td>{{ car.steerable_axle_number }}</td></tr>
    <tr><td>Supply Contract Number, Date:</td><td>{% if car.supply_contract %}{{ car.supply_contract }}
        {% else %}Not Available{% endif %}</td></tr>
    <tr><td>Date of Shipment from the Factory:</td><td>{% if car.date_of_shipment_from_the_factory %}
        {{ car.date_of_shipment_from_the_factory|date:"d.m.Y" }}{% else %}Not Available{% endif %}</td></tr>
    <tr><td>Consignee:</td><td>{% if car.consignee %}{{ car.consignee }}{% else %}Not Available{% endif %}</td></tr>
    <tr><td>Delivery Address (Usage):</td><td>{% if car.delivery_address %}{{ car.delivery_address }}
        {% else %}Not Available{% endif %}</td></tr>
    <tr><td>Equipment (Additional Options):</td><td>{% if car.equipment %}{{ car.equipment }}{% else %}Not Available
        {% endif %}</td></tr>
    <tr><td>Client:</td><td>{% if car.client %}{{ car.client }}{% else %}Not Available{% endif %}</td></tr>
    <tr><td>Service Organization:</td><td>{% if car.service_company %}<a href="#" data-bs-toggle="modal" data-bs-target="#service_company"><b>{{ car.service_company }}</b></a>{% else %}Not Available
        {% endif %}</td></tr>
    </table>
</div>

<br>
<div class="center">
    <a href="{% url 'info' %}" class=" button medium">Back</a>
    {% if perms.silant.change_car %}
        <a href="{{ request.path }}/edit" class="button medium">Edit</a>
    {% endif %}
    {% if perms.silant.delete_car %}
        <a href="{{ request.path }}/delete" class="button medium">Delete</a>
    {% endif %}
</div>

<div class="modal" tabindex="-1" id="technique_model">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Description from the Directory:<br><br>
        {% if car.technique_model.description %}
            {{ car.technique_model.description }}
        {% else %}
            Description not available :(
        {% endif %}
        <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" tabindex="-1" id="engine_model">
  <div class modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Description from the Directory:<br><br>
        {% if car.engine_model.description %}
            {{ car.engine_model.description }}
        {% else %}
            Description not available :(
        {% endif %}
        <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" tabindex="-1" id="transmission_model">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Description from the Directory:<br><br>
        {% if car.transmission_model.description %}
            {{ car.transmission_model.description }}
        {% else %}
            Description not available :(
        {% endif %}
        <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" tabindex="-1" id="drive_axle_model">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Description from the Directory:<br><br>
        {% if car.drive_axle_model.description %}
            {{ car.drive_axle_model.description }}
        {% else %}
            Description not available :(
        {% endif %}
        <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" tabindex="-1" id="steerable_axle_model">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Description from the Directory:<br><br>
        {% if car.steerable_axle_model.description %}
            {{ car.steerable_axle_model.description }}
        {% else %}
            Description not available :(
        {% endif %}
        <br><br><button type=" button medium" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" tabindex="-1" id="service_company">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Description from the Directory:<br><br>
        {% if car.service_company.description %}
            {{ car.service_company.description }}
        {% else %}
            Description not available :(
        {% endif %}
        <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

silant_main/services/templates/complaints_item.html
{% extends 'default.html' %}
{% load auth_extras %}
{% load bootstrap5 %}
{% block bootstrap_css %}{% bootstrap_css %}{% bootstrap_javascript %}{% endblock bootstrap_css %}

{% block content %}

<h5 class="center">Complaint Data:</h5>
<div class="center">
    <table style="border-bottom: none; border-top: none;">
    <tr><td>Machine Factory Number:</td><td>{{ complaints.car }}</td></tr>
    <tr><td>Service Company:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#service_company"><b>{{ complaints.service_company }}</b></a></td></tr>
    <tr><td>Refusal Date:</td><td>{{ complaints.date_of_refusal }}</td></tr>
    <tr><td>Operating Hours:</td><td>{{ complaints.operating_time }}</td></tr>
    <tr><td>Failure Node:</td><td>{{ complaints.failure_node }}</td></tr>
    <tr><td>Failure Character:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#description_failure"><b>{{ complaints.description_failure }}</b></a></td></tr>
    <tr><td>Recovery Method:</td><td><a href="#" data-bs-toggle="modal" data-bs-target="#recovery_method"><b>{{ complaints.recovery_method }}</b></a></td></tr>
    <tr><td>Used Spare Parts:</td><td>{{ complaints.parts_used }}</td></tr>
    <tr><td>Restoration Date:</td><td>{{ complaints.date_of_restoration }}</td></tr>
    <tr><td>Equipment Downtime:</td><td>{{ complaints.equipment_downtime }}</td></tr>
    </table>
</div>
<br>
<div class="center">
    <a href="{% url 'complaints' %}" class="button medium">Back</a>
    {% if perms.services.change_complaints %}
        <a href="{{ request.get_full_path }}/edit" class="button medium">Edit</a>
    {% endif %}
    {% if perms.services.delete_complaints %}
        <a href="{{ request.get_full_path }}/delete" class="button medium">Delete</a>
    {% endif %}
</div>

<div class="modal" tabindex="-1" id="service_company">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Description from the Directory:<br><br>
        {% if complaints.service_company.description %}
            {{ complaints.service_company.description }}
        {% else %}
            Description not available :(
        {% endif %}
        <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" tabindex="-1" id="description_failure">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Description from the Directory:<br><br>
        {% if complaints.description_failure.description %}
            {{ complaints.description_failure.description }}
        {% else %}
            Description not available :(
        {% endif %}
        <br><br><button type="button" class "button medium" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" tabindex="-1" id="recovery_method">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Description from the Directory:<br><br>
        {% if complaints.recovery_method.description %}
            {{ complaints.recovery_method.description }}
        {% else %}
            Description not available :(
        {% endif %}
        <br><br><button type="button" class="button medium" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

silant_main/services/templates/create_car.html
{% extends 'default.html' %}
{% load bootstrap5 %}
{% block bootstrap_css %}{% bootstrap_css %}{% endblock bootstrap_css %}
{% load auth_extras %}

{% block content %}
<h4 class="center">Machine Parameters:</h4>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <div class="center">
            {% buttons %}
            <a class="button medium" href="{% url 'info' %}" role="button">Cancel</a>
            <button type="submit" class="button medium">Save</button>
            {% endbuttons %}
        </div>
    </form>
{% endblock content %}

silant_main/services/templates/create_complaints.html
{% extends 'default.html' %}
{% load bootstrap5 %}
{% block bootstrap_css %}{% bootstrap_css %}{% endblock bootstrap_css %}
{% load auth_extras %}

{% block content %}
    <div class="left-right">
        <p class="select_car">Select a Machine</p>
        <select class="form-select" style='margin: 0 0 5px 25px;' onchange="window.location.href = this.options[this.selectedIndex].value">
            <option value="{{select_car.id}}">{{ select_car }}</option>
            {% for car in cars %}
                {% if car.id != select_car.id %}
                    <option value="?id={{car.id}}">{{ car.factory_number }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <div class="center">
            {% buttons %}
            <a class="button medium" href="{% url 'complaints' %}" role="button">Cancel</a>
            <button type="submit" class a="button medium">Save</button>
            {% endbuttons %}
        </div>
    </form>
{% endblock content %}